/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchChannelIdRouteImport } from './routes/watch.$channelId'
import { Route as EmbedChannelIdRouteImport } from './routes/embed.$channelId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchChannelIdRoute = WatchChannelIdRouteImport.update({
  id: '/watch/$channelId',
  path: '/watch/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedChannelIdRoute = EmbedChannelIdRouteImport.update({
  id: '/embed/$channelId',
  path: '/embed/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/embed/$channelId': typeof EmbedChannelIdRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/embed/$channelId': typeof EmbedChannelIdRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/embed/$channelId': typeof EmbedChannelIdRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/studio'
    | '/terms'
    | '/embed/$channelId'
    | '/watch/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/studio'
    | '/terms'
    | '/embed/$channelId'
    | '/watch/$channelId'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/studio'
    | '/terms'
    | '/embed/$channelId'
    | '/watch/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  EmbedChannelIdRoute: typeof EmbedChannelIdRoute
  WatchChannelIdRoute: typeof WatchChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$channelId': {
      id: '/watch/$channelId'
      path: '/watch/$channelId'
      fullPath: '/watch/$channelId'
      preLoaderRoute: typeof WatchChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$channelId': {
      id: '/embed/$channelId'
      path: '/embed/$channelId'
      fullPath: '/embed/$channelId'
      preLoaderRoute: typeof EmbedChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  EmbedChannelIdRoute: EmbedChannelIdRoute,
  WatchChannelIdRoute: WatchChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
