/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchChannelIdRouteImport } from './routes/watch.$channelId'
import { Route as EmbedChannelIdRouteImport } from './routes/embed.$channelId'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchChannelIdRoute = WatchChannelIdRouteImport.update({
  id: '/watch/$channelId',
  path: '/watch/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedChannelIdRoute = EmbedChannelIdRouteImport.update({
  id: '/embed/$channelId',
  path: '/embed/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/studio': typeof StudioRoute
  '/embed/$channelId': typeof EmbedChannelIdRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/studio': typeof StudioRoute
  '/embed/$channelId': typeof EmbedChannelIdRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/studio': typeof StudioRoute
  '/embed/$channelId': typeof EmbedChannelIdRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/studio'
    | '/embed/$channelId'
    | '/watch/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/faq' | '/studio' | '/embed/$channelId' | '/watch/$channelId'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/studio'
    | '/embed/$channelId'
    | '/watch/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  StudioRoute: typeof StudioRoute
  EmbedChannelIdRoute: typeof EmbedChannelIdRoute
  WatchChannelIdRoute: typeof WatchChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$channelId': {
      id: '/watch/$channelId'
      path: '/watch/$channelId'
      fullPath: '/watch/$channelId'
      preLoaderRoute: typeof WatchChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$channelId': {
      id: '/embed/$channelId'
      path: '/embed/$channelId'
      fullPath: '/embed/$channelId'
      preLoaderRoute: typeof EmbedChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  StudioRoute: StudioRoute,
  EmbedChannelIdRoute: EmbedChannelIdRoute,
  WatchChannelIdRoute: WatchChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
